### ISSUE TITLE
Please update to .Net Core 1.1

### ISSUE THREAD

**Issue by gilbertogwa** [autofac/Autofac.Extras.DynamicProxy#18] opened 2016-11-28 19:58 UTC
The dependency Autofac.Extras.DynamicProxy 4.1.0 does not support framework .NETCoreApp,Version=v1.1

**Comment by tillig** [comment] 2016-11-28 20:00
Duplicate of #8.

We can't support .NET Core until Castle.Core updates. Follow #8 if you're interested in tracking that progress.

**Closed as completed by tillig** 2016-11-28 20:00 UTC
Labels: duplicate
