### ISSUE TITLE
Castle.Core version 4.0.0 causes NuGet dependency warnings

### ISSUE THREAD

**Issue by peter-erikson** [autofac/Autofac.Extras.DynamicProxy#24] opened 2018-02-09 14:02 UTC
The castle.Core version used in Autofac.Extras.DynamicProxy is casing dependency warnings.

warning NU1603: Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.

https://github.com/autofac/Autofac.Extras.DynamicProxy/blob/aae337d1ef1f72220eea3be379374404462d1f6f/src/Autofac.Extras.DynamicProxy/Autofac.Extras.DynamicProxy.csproj#L35

It has been fixed in Castle.Core 4.1.0. Please consider updating to a newer version.

**Comment by tillig** [comment] 2018-02-09 16:05
Duplicate of #19. Though admittedly this seems to be getting enough people that forcing the consumer to upgrade to Castle.Core 4.1.0 might be worth it even if we don't actually require functionality from the updated Castle.

**Closed as completed by tillig** 2018-02-09 16:05 UTC
