### ISSUE TITLE
Warning NU1603	Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) 

### ISSUE THREAD

**Issue by ghost** [autofac/Autofac.Extras.DynamicProxy#20] opened 2017-09-07 13:16 UTC
Warning	NU1603	Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.

![image](https://user-images.githubusercontent.com/7701377/30165172-66f678aa-93df-11e7-8d64-a32d05ecd26e.png)

.Net Core 2.0 app

**Comment by tillig** [comment] 2017-09-07 15:16
Duplicate of #19. This is a Castle.Core issue, not Autofac. We depend on Castle.Core, we don't own Castle.Core.

**Closed as completed by tillig** 2017-09-07 15:16 UTC

**Comment by ghost** [comment] 2017-09-07 15:22
Yes, I know, why you not upgrade dependency - Castle.Core to 4.1?

**Comment by tillig** [comment] 2017-09-07 15:30
Libraries are generally recommended to use the lowest version that is compatible with the required features. We don't want to force people to take upgrades they don't need. It's the same reason many ASP.NET Core assemblies don't just upgrade straight to ASP.NET Core 2.0 - it'd force consumers of the libraries to take big, potentially breaking upgrades. If you want to take the upgrade yourself, do it - that's your choice.

**Comment by jaroslawpedrycz** [comment] 2017-09-07 15:30
<PackageReference Include="Castle.Core" Version="4.0.0" />

**Comment by tiddlypip** [comment] 2024-05-31 14:25
Seems like its a mistake as there is no version 4.0.1 of System.ComponentModel.TypeConverter
